//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterAllevitionFoundationproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsDonationstbl
    {
        public int GoodsID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> NumberOfItems { get; set; }
        public string Category { get; set; }
        public string Donar { get; set; }
    }
}
