//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterAllevitionFoundationproject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DisasterAlleviationFoundationDBEntities : DbContext
    {
        public DisasterAlleviationFoundationDBEntities()
            : base("name=DisasterAlleviationFoundationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disastertbl> Disastertbls { get; set; }
        public virtual DbSet<GoodsDonationstbl> GoodsDonationstbls { get; set; }
        public virtual DbSet<MonetaryDonationsTbl> MonetaryDonationsTbls { get; set; }
    }
}
